/**
 * Compiler types for the local ResearchTex Agent (Phase 4+).
 *
 * The web app communicates with the local Tauri-based agent through a
 * controlled HTTP interface on localhost. The agent validates all paths
 * and commands — the browser never executes arbitrary shell commands.
 */

// ─── Engine ───────────────────────────────────────────────────────────────────

/** Supported LaTeX compilation engines. */
export type CompilerEngine =
  | "pdflatex"
  | "xelatex"
  | "lualatex";

/** Supported bibliography processors. */
export type BibProcessor = "bibtex" | "biber";

// ─── Health ───────────────────────────────────────────────────────────────────

/** Health status of the local agent. */
export interface AgentHealthStatus {
  readonly isRunning: boolean;
  readonly version: string;
  /** Detected installed LaTeX distribution, if any. */
  readonly latexDistribution?: "texlive" | "miktex" | "unknown";
  readonly availableEngines: readonly CompilerEngine[];
}

// ─── Compile ─────────────────────────────────────────────────────────────────

export interface CompileRequestFile {
  /** Relative path of the file inside the project workspace (e.g., "main.tex" or "chapters/intro.tex"). */
  readonly path: string;
  /** Content of the file (Base64 if isBinary, UTF-8 string otherwise). */
  readonly content: string;
  /** True if the content is Base64 encoded binary data. */
  readonly isBinary: boolean;
}

/** A compile job request sent to the local agent. */
export interface CompileRequest {
  /** Unique ID generated by the web app for this job. */
  readonly jobId: string;
  /** Root .tex file, relative to project root. */
  readonly rootFile: string;
  readonly engine: CompilerEngine;
  readonly bibProcessor?: BibProcessor;
  /** Run BibTeX/Biber pass automatically if needed. */
  readonly runBib: boolean;
  /** Number of compile passes (default 2 for cross-references). */
  readonly passes?: number;
  /** Complete snapshot of all project files to compile. */
  readonly files?: readonly CompileRequestFile[];
}

/** Status of a compile job. */
export type CompileJobStatus =
  | "queued"
  | "running"
  | "success"
  | "error"
  | "cancelled";

/** Result returned after compilation completes. */
export interface CompileResult {
  readonly jobId: string;
  readonly status: CompileJobStatus;
  /** Base64-encoded contents of the generated PDF, if successful. */
  readonly pdfBase64?: string;
  readonly durationMs: number;
  readonly logEntries: readonly CompileLogEntry[];
}

// ─── Logs ─────────────────────────────────────────────────────────────────────

export type CompileLogLevel = "info" | "warning" | "error";

/** A single parsed log entry from the LaTeX compiler. */
export interface CompileLogEntry {
  readonly level: CompileLogLevel;
  readonly message: string;
  /** Source file where the issue occurred, if available. */
  readonly file?: string;
  /** Line number in the source file, if available. */
  readonly line?: number;
}

// ─── Client Interface ─────────────────────────────────────────────────────────

/** Client interface for communicating with the local Rust compiler agent. */
export interface CompilerClient {
  /** Checks the health and connectivity of the compiler agent. */
  health(): Promise<AgentHealthStatus>;
  
  /** Sends a project to the local agent for compilation. */
  compile(request: CompileRequest): Promise<CompileResult>;
  
  /** Requests cancellation of an ongoing compilation job. */
  cancel(jobId: string): Promise<void>;
}
